import Head from 'next/head';
import styles from 'styles/Home.module.css';
import dbConnect from '../lib/dbConnect';
import Test from '../model/Test';

export default async function page() {
  await dbConnect();
  let docs = await Test.find();
  if (!docs) return null;
  return (
    <div>
      <Head>
        <title>Marathon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hola putita!</h1>
      </main>
      <div>
        {docs.map((test: any) => (
          <div key={test.id}>{test.field}</div>
        ))}
      </div>
    </div>
  );
}
